import os
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet

from src.dashboard.utils.db import run_query


OUTPUT_DIR = "reports/portfolio"

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)


OUTPUT_FILE = (
    "reports/portfolio/"
    "portfolio_summary.pdf"
)


def trend_arrow(value):

    if value > 2:
        return "↑"
    elif value < -2:
        return "↓"
    else:
        return "→"



def generate():

    doc = SimpleDocTemplate(
        OUTPUT_FILE
    )


    styles = getSampleStyleSheet()

    story = []


    companies = run_query(
        """
        SELECT
            company_name,
            id,
            roe_percentage,
            roce_percentage,
            book_value,
            face_value
        FROM companies
        ORDER BY company_name
        """
    )


    sectors = run_query(
        """
        SELECT
            company_id,
            broad_sector
        FROM sectors
        """
    )


    for _,company in companies.iterrows():


        company_id = company["id"]


        sector = sectors[
            sectors["company_id"] == company_id
        ]


        sector_name = (
            sector.iloc[0]["broad_sector"]
            if len(sector)>0
            else "Unknown"
        )


        story.append(
            Paragraph(
                f"{company['company_name']} ({company_id})",
                styles["Title"]
            )
        )


        story.append(
            Paragraph(
                f"Sector: {sector_name}",
                styles["Heading2"]
            )
        )


        story.append(
            Spacer(1,20)
        )


        data = [
            [
                "KPI",
                "Value",
                "Trend"
            ],
            [
                "ROE",
                f"{company['roe_percentage']}%",
                "→"
            ],
            [
                "ROCE",
                f"{company['roce_percentage']}%",
                "→"
            ],
            [
                "Book Value",
                str(company["book_value"]),
                "→"
            ],
            [
                "Face Value",
                str(company["face_value"]),
                "→"
            ],
        ]


        table = Table(
            data
        )


        table.setStyle(
            TableStyle(
                [
                    (
                    "GRID",
                    (0,0),
                    (-1,-1),
                    0.5,
                    None
                    ),
                    (
                    "VALIGN",
                    (0,0),
                    (-1,-1),
                    "TOP"
                    )
                ]
            )
        )


        story.append(table)


        story.append(
            Spacer(1,30)
        )


        story.append(
            Paragraph(
                "Generated by Nifty 100 Financial Analytics Platform",
                styles["Normal"]
            )
        )


        story.append(
            PageBreak()
        )


    doc.build(
        story
    )


    print(
        "Generated:",
        OUTPUT_FILE
    )



if __name__ == "__main__":
    generate()